server:
  port: 8080

spring:
  application:
    name: oneplane

  profiles:
    include: secret

  # JSP ?? ??
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# MyBatis ?? ??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.oneplane.dto
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30

# ?? ?? ??
logging:
  level:
    com.oneplane: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG