server:
  port: 8080
  servlet:
    session:
      cookie:
        name: JSESSIONID
        path: /
        http-only: true
        secure: false
        same-site: Lax
  error:
    include-message: always
    include-binding-errors: always
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600  # 1시간 캐싱

spring:
  application:
    name: oneplane

  profiles:
    include: secret

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 1MB

# JSP
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# MyBatis 설정
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.oneplane.*.domain

# 파일 업로드
file:
  upload:
    path: ./uploads/
    url: /uploads/

logging:
  level:
    com.oneplane: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG

# 외교부_국가별 기본정보 API 인코딩 키
api:
  country:
    key: MC1h4938TtXp1nuIE6%2F9QqHUBp%2BJqtdX3%2FEK%2BZT9ZeyiNvWlQGyN0%2FptcDTNgcS31KJ9qk1Fv6hlpw1WVPXYBQ%3D%3D