spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    username: oneplane
    password: oneplane123
    driver-class-name: oracle.jdbc.OracleDriver

    # OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 150cfc9af01c1f4565ab894ffe8f6b5c
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id