server:
  port: 8080
  servlet:
    session:
      cookie:
        name: JSESSIONID
        path: /
        http-only: true
        secure: false
        same-site: Lax
  error:
    include-message: always
    include-binding-errors: always
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600  # 1시간 캐싱

spring:
  application:
    name: oneplane

  profiles:
    include: secret

# JSP
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# MyBatis 설정
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.oneplane.*.domain

logging:
  level:
    com.oneplane: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG